import { 
  Loja, 
  Funcionario, 
  Cliente, 
  ReceitaOptica, 
  OrdemServicoOptica, 
  Produto, 
  Laboratorio, 
  VendaPDV, 
  TransacaoFinanceira 
} from '../types';

export const INITIAL_LOJAS: Loja[] = [
  {
    id: 'loja-matriz-01',
    nome_fantasia: 'Ótica Visão Prime - Matriz Centro',
    razao_social: 'Visão Prime Comércio de Óptica Ltda',
    cnpj: '12.345.678/0001-90',
    telefone: '(11) 3456-7890',
    email: 'contato@visaoprime.com.br',
    endereco: 'Rua das Flores, 450 - Centro',
    cidade: 'São Paulo',
    uf: 'SP',
    plano: 'pro',
    status: 'ativo',
    trial_ate: '2026-12-31T23:59:59Z',
    config_impressao: {
      largura_mm: 80,
      imprimir_grade_grau: true,
      imprimir_termo_garantia: true,
      mensagem_rodape: 'Obrigado por escolher a Visão Prime! Garantia de 1 ano nas lentes.'
    }
  },
  {
    id: 'loja-filial-02',
    nome_fantasia: 'Ótica Visão Prime - Filial Shopping',
    razao_social: 'Visão Prime Comércio de Óptica Ltda',
    cnpj: '12.345.678/0002-71',
    telefone: '(11) 3456-7899',
    email: 'shopping@visaoprime.com.br',
    endereco: 'Av. Paulista, 1000 - Loja 240',
    cidade: 'São Paulo',
    uf: 'SP',
    plano: 'pro',
    status: 'ativo',
    trial_ate: '2026-12-31T23:59:59Z',
  }
];

export const INITIAL_FUNCIONARIOS: Funcionario[] = [
  {
    id: 'func-01',
    loja_id: 'loja-matriz-01',
    nome: 'Carlos Eduardo Mendes',
    email: 'carlos@visaoprime.com.br',
    cargo: 'ADMIN',
    comissao_produto_pct: 4.0,
    comissao_servico_pct: 6.0,
    permissoes: {
      dashboard: true,
      clientes: true,
      receitas: true,
      os: true,
      pdv: true,
      estoque: true,
      laboratorios: true,
      financeiro: true,
      configuracoes: true
    },
    ativo: true
  },
  {
    id: 'func-02',
    loja_id: 'loja-matriz-01',
    nome: 'Dra. Vanessa Lima',
    email: 'vanessa.optometria@visaoprime.com.br',
    cargo: 'OPTOMETRISTA',
    comissao_produto_pct: 0.0,
    comissao_servico_pct: 15.0,
    permissoes: {
      dashboard: true,
      clientes: true,
      receitas: true,
      os: true,
      pdv: false,
      estoque: false,
      laboratorios: false,
      financeiro: false,
      configuracoes: false
    },
    ativo: true
  },
  {
    id: 'func-03',
    loja_id: 'loja-matriz-01',
    nome: 'Juliana Rocha (Consultora)',
    email: 'juliana@visaoprime.com.br',
    cargo: 'VENDEDOR',
    comissao_produto_pct: 5.0,
    comissao_servico_pct: 5.0,
    permissoes: {
      dashboard: true,
      clientes: true,
      receitas: true,
      os: true,
      pdv: true,
      estoque: true,
      laboratorios: false,
      financeiro: false,
      configuracoes: false
    },
    ativo: true
  },
  {
    id: 'func-04',
    loja_id: 'loja-matriz-01',
    nome: 'Roberto Silva (Montador)',
    email: 'roberto.lab@visaoprime.com.br',
    cargo: 'TECNICO_MONTAGEM',
    comissao_produto_pct: 0.0,
    comissao_servico_pct: 8.0,
    permissoes: {
      dashboard: true,
      clientes: false,
      receitas: true,
      os: true,
      pdv: false,
      estoque: true,
      laboratorios: true,
      financeiro: false,
      configuracoes: false
    },
    ativo: true
  }
];

export const INITIAL_CLIENTES: Cliente[] = [
  {
    id: 'cli-01',
    loja_id: 'loja-matriz-01',
    nome: 'Mariana Silveira Albuquerque',
    cpf: '321.654.987-00',
    data_nascimento: '1988-04-12',
    telefone: '(11) 98765-4321',
    whatsapp: '5511987654321',
    email: 'mariana.silveira@email.com',
    cep: '01310-100',
    endereco: 'Rua Bela Cintra',
    numero: '780',
    bairro: 'Consolação',
    cidade: 'São Paulo',
    uf: 'SP',
    origem: 'INDICAÇÃO MÉDICA',
    observacoes: 'Sensibilidade à luz azul (trabalha 10h no computador). Preferência por armações leves.',
    created_at: '2026-01-15T10:00:00Z'
  },
  {
    id: 'cli-02',
    loja_id: 'loja-matriz-01',
    nome: 'Rodrigo Augusto Fontana',
    cpf: '456.789.123-11',
    data_nascimento: '1975-09-23',
    telefone: '(11) 97123-8899',
    whatsapp: '5511971238899',
    email: 'rodrigo.fontana@empresa.com.br',
    cep: '04543-011',
    endereco: 'Av. Brigadeiro Faria Lima',
    numero: '2200',
    bairro: 'Itaim Bibi',
    cidade: 'São Paulo',
    uf: 'SP',
    origem: 'INSTAGRAM',
    observacoes: 'Usa multifocal há 3 anos. Deseja campo visual amplo para direção noturna.',
    created_at: '2026-02-10T14:30:00Z'
  },
  {
    id: 'cli-03',
    loja_id: 'loja-matriz-01',
    nome: 'Ana Clara Prado Ramos',
    cpf: '789.123.456-22',
    data_nascimento: '2002-11-05',
    telefone: '(11) 99444-1122',
    whatsapp: '5511994441122',
    email: 'anaclara.prado@gmail.com',
    cidade: 'São Paulo',
    uf: 'SP',
    origem: 'BALCÃO',
    observacoes: 'Miopia moderada. Busca armação solar com grau espelhado.',
    created_at: '2026-03-01T09:15:00Z'
  }
];

export const INITIAL_RECEITAS: ReceitaOptica[] = [
  {
    id: 'rec-01',
    loja_id: 'loja-matriz-01',
    cliente_id: 'cli-01',
    cliente_nome: 'Mariana Silveira Albuquerque',
    medico_prescritor: 'Dr. Fernando Arantes',
    registro_profissional: 'CRM-SP 145.892',
    tipo_prescritor: 'OFTALMOLOGISTA',
    data_emissao: '2026-09-10',
    data_validade: '2027-09-10',
    od_longe: {
      esferico: -2.25,
      cilindrico: -0.75,
      eixo: 95,
      dnp: 31.5,
      altura: 19.0
    },
    oe_longe: {
      esferico: -2.50,
      cilindrico: -1.00,
      eixo: 85,
      dnp: 32.0,
      altura: 19.0
    },
    tipo_lente_sugerida: 'MONOFOCAL',
    observacoes: 'Prescrever antirreflexo com proteção Blue UV Filter.',
    created_at: '2026-09-10T11:00:00Z'
  },
  {
    id: 'rec-02',
    loja_id: 'loja-matriz-01',
    cliente_id: 'cli-02',
    cliente_nome: 'Rodrigo Augusto Fontana',
    medico_prescritor: 'Dra. Vanessa Lima',
    registro_profissional: 'CROO-SP 0841',
    tipo_prescritor: 'OPTOMETRISTA',
    data_emissao: '2026-09-18',
    data_validade: '2027-09-18',
    od_longe: {
      esferico: +1.50,
      cilindrico: -0.50,
      eixo: 180,
      adicao: 2.25,
      dnp: 33.0,
      altura: 21.0
    },
    oe_longe: {
      esferico: +1.75,
      cilindrico: -0.50,
      eixo: 175,
      adicao: 2.25,
      dnp: 33.5,
      altura: 21.0
    },
    tipo_lente_sugerida: 'MULTIFOCAL',
    observacoes: 'Paciente relata astenopia ao ler tablet. Recomenda-se corredor progressivo suave.',
    created_at: '2026-09-18T15:20:00Z'
  }
];

export const INITIAL_LABORATORIOS: Laboratorio[] = [
  {
    id: 'lab-01',
    loja_id: 'loja-matriz-01',
    nome: 'Essilor Digital Surfacing Lab',
    contato: 'Marcos / Expedição',
    telefone: '(11) 2199-8800',
    email: 'pedidos@essilorlab.com.br',
    prazo_medio_dias: 3,
    tabela_precos_resumo: 'Varilux Physio / Comfort / Eyezen + Crizal Rock',
    total_pedidos_ativos: 4
  },
  {
    id: 'lab-02',
    loja_id: 'loja-matriz-01',
    nome: 'Zeiss Vision Care Brasil',
    contato: 'Patrícia Atendimento',
    telefone: '(11) 3004-9347',
    email: 'lab.brasil@zeiss.com',
    prazo_medio_dias: 4,
    tabela_precos_resumo: 'Zeiss SmartLife / DriveSafe + DuraVision Platinum',
    total_pedidos_ativos: 2
  },
  {
    id: 'lab-03',
    loja_id: 'loja-matriz-01',
    nome: 'Hoya Lens Express',
    contato: 'Renato Suporte',
    telefone: '(11) 4003-1288',
    email: 'express@hoya.com.br',
    prazo_medio_dias: 2,
    tabela_precos_resumo: 'Hoyalux iD Myself / Balansis + LongLife AR',
    total_pedidos_ativos: 1
  }
];

export const INITIAL_PRODUTOS: Produto[] = [
  {
    id: 'prod-01',
    loja_id: 'loja-matriz-01',
    codigo_barras: '789891230001',
    codigo_referencia: 'RB5154-2000',
    nome: 'Armação Ray-Ban Clubmaster Acetato Preto',
    tipo: 'ARMACAO_GRAU',
    marca: 'Ray-Ban',
    modelo: 'Clubmaster Classic',
    cor: 'Preto / Dourado',
    material: 'Acetato com Metal',
    tamanho_aro: 51,
    tamanho_ponte: 21,
    tamanho_haste: 145,
    preco_custo: 280.00,
    preco_venda: 790.00,
    estoque_atual: 5,
    estoque_minimo: 2,
    ativo: true
  },
  {
    id: 'prod-02',
    loja_id: 'loja-matriz-01',
    codigo_barras: '789891230002',
    codigo_referencia: 'OX8156-0154',
    nome: 'Armação Oakley Holbrook RX Titânio Grafite',
    tipo: 'ARMACAO_GRAU',
    marca: 'Oakley',
    modelo: 'Holbrook RX',
    cor: 'Satin Black',
    material: 'O Matter / Titânio',
    tamanho_aro: 54,
    tamanho_ponte: 18,
    tamanho_haste: 137,
    preco_custo: 310.00,
    preco_venda: 850.00,
    estoque_atual: 4,
    estoque_minimo: 2,
    ativo: true
  },
  {
    id: 'prod-03',
    loja_id: 'loja-matriz-01',
    codigo_barras: '789891230003',
    codigo_referencia: 'VO5338-W44',
    nome: 'Armação Vogue Eyewear Feminina Tartaruga',
    tipo: 'ARMACAO_GRAU',
    marca: 'Vogue',
    modelo: 'Cat Eye Modern',
    cor: 'Havana / Tartaruga',
    material: 'Acetato Nobre',
    tamanho_aro: 53,
    tamanho_ponte: 16,
    tamanho_haste: 140,
    preco_custo: 190.00,
    preco_venda: 540.00,
    estoque_atual: 8,
    estoque_minimo: 3,
    ativo: true
  },
  {
    id: 'prod-04',
    loja_id: 'loja-matriz-01',
    codigo_barras: '789891230004',
    codigo_referencia: 'LNT-VAR-COMF',
    nome: 'Par de Lentes Varilux Comfort Max Resina 1.59 Policarbonato Crizal Rock',
    tipo: 'LENTE_OFTALMICA',
    marca: 'Essilor',
    modelo: 'Comfort Max Digital',
    preco_custo: 480.00,
    preco_venda: 1490.00,
    estoque_atual: 20,
    estoque_minimo: 5,
    ativo: true
  },
  {
    id: 'prod-05',
    loja_id: 'loja-matriz-01',
    codigo_barras: '789891230005',
    codigo_referencia: 'LNT-ZEI-SMRT',
    nome: 'Par de Lentes Zeiss SmartLife Monofocal Alto Índice 1.67 DuraVision Platinum',
    tipo: 'LENTE_OFTALMICA',
    marca: 'Zeiss',
    modelo: 'SmartLife Single Vision',
    preco_custo: 390.00,
    preco_venda: 1250.00,
    estoque_atual: 15,
    estoque_minimo: 5,
    ativo: true
  },
  {
    id: 'prod-06',
    loja_id: 'loja-matriz-01',
    codigo_barras: '789891230006',
    codigo_referencia: 'RB2140-901',
    nome: 'Óculos Solar Ray-Ban Wayfarer Classic G-15',
    tipo: 'SOLAR',
    marca: 'Ray-Ban',
    modelo: 'Original Wayfarer',
    cor: 'Black / Green Classic G-15',
    material: 'Acetato',
    tamanho_aro: 50,
    tamanho_ponte: 22,
    tamanho_haste: 150,
    preco_custo: 350.00,
    preco_venda: 920.00,
    estoque_atual: 6,
    estoque_minimo: 2,
    ativo: true
  },
  {
    id: 'prod-07',
    loja_id: 'loja-matriz-01',
    codigo_barras: '789891230007',
    codigo_referencia: 'AC-LIMPA-LENTES',
    nome: 'Spray Limpa Lentes Anti-Embaçante 60ml + Flanela Microfibra',
    tipo: 'ACESSORIO',
    marca: 'Visão Prime Care',
    preco_custo: 4.50,
    preco_venda: 25.00,
    estoque_atual: 45,
    estoque_minimo: 15,
    ativo: true
  }
];

export const INITIAL_ORDENS_SERVICO: OrdemServicoOptica[] = [
  {
    id: 'os-01',
    loja_id: 'loja-matriz-01',
    numero_os: 1042,
    cliente_id: 'cli-01',
    cliente_nome: 'Mariana Silveira Albuquerque',
    cliente_telefone: '(11) 98765-4321',
    receita_id: 'rec-01',
    atendente_id: 'func-03',
    atendente_nome: 'Juliana Rocha (Consultora)',
    montador_id: 'func-04',
    montador_nome: 'Roberto Silva (Montador)',
    laboratorio_id: 'lab-02',
    laboratorio_nome: 'Zeiss Vision Care Brasil',
    numero_pedido_laboratorio: 'ZS-2026-9812',
    status: 'EM_SURFACAGEM',
    
    armacao_descricao: 'Armação Ray-Ban Clubmaster Acetato Preto (RB5154-2000)',
    armacao_referencia: 'RB5154-2000',
    armacao_propria: false,
    
    lente_descricao: 'Zeiss SmartLife Monofocal Alto Índice 1.67',
    lente_material: 'ALTO_INDICE_1.67',
    lente_design: 'MONOFOCAL',
    tratamentos: ['Anti-Reflexo DuraVision Platinum', 'BlueProtect UV', 'Camada Hidrofóbica'],
    
    aro_horizontal_mm: 51.0,
    aro_vertical_mm: 39.0,
    ponte_mm: 21.0,
    maior_diagonal_mm: 54.5,
    dnp_od: 31.5,
    dnp_oe: 32.0,
    altura_od: 19.0,
    altura_oe: 19.0,
    
    valor_armacao: 790.00,
    valor_lentes: 1250.00,
    valor_tratamentos: 200.00,
    valor_servicos_montagem: 50.00,
    custo_laboratorio_estimado: 390.00,
    valor_desconto: 100.00,
    valor_total: 2190.00,
    
    data_abertura: '2026-09-24T10:30:00Z',
    data_prometida: '2026-09-29T18:00:00Z',
    data_laboratorio_retorno: '2026-09-28T14:00:00Z',
    observacoes_internas: 'Cliente solicitou conferência rigorosa de alinhamento pantoscópico.',
    created_at: '2026-09-24T10:30:00Z'
  },
  {
    id: 'os-02',
    loja_id: 'loja-matriz-01',
    numero_os: 1043,
    cliente_id: 'cli-02',
    cliente_nome: 'Rodrigo Augusto Fontana',
    cliente_telefone: '(11) 97123-8899',
    receita_id: 'rec-02',
    atendente_id: 'func-03',
    atendente_nome: 'Juliana Rocha (Consultora)',
    laboratorio_id: 'lab-01',
    laboratorio_nome: 'Essilor Digital Surfacing Lab',
    numero_pedido_laboratorio: 'ESS-44109',
    status: 'AGUARDANDO_LABORATORIO',
    
    armacao_descricao: 'Armação Oakley Holbrook RX Titânio Grafite',
    armacao_referencia: 'OX8156-0154',
    armacao_propria: false,
    
    lente_descricao: 'Varilux Comfort Max Resina 1.59 Policarbonato Crizal Rock',
    lente_material: 'POLICARBONATO_1.59',
    lente_design: 'MULTIFOCAL_PROGRESSIVA',
    tratamentos: ['Anti-Reflexo Crizal Rock', 'Proteção 100% UVA/UVB', 'Transitions Signature Gen 8 Cinza'],
    
    aro_horizontal_mm: 54.0,
    aro_vertical_mm: 41.0,
    ponte_mm: 18.0,
    maior_diagonal_mm: 58.0,
    dnp_od: 33.0,
    dnp_oe: 33.5,
    altura_od: 21.0,
    altura_oe: 21.0,
    
    valor_armacao: 850.00,
    valor_lentes: 1490.00,
    valor_tratamentos: 450.00,
    valor_servicos_montagem: 60.00,
    custo_laboratorio_estimado: 580.00,
    valor_desconto: 150.00,
    valor_total: 2700.00,
    
    data_abertura: '2026-09-25T14:15:00Z',
    data_prometida: '2026-10-02T18:00:00Z',
    observacoes_internas: 'Aguardando envio pelo malote das 17h para o lab Essilor.',
    created_at: '2026-09-25T14:15:00Z'
  },
  {
    id: 'os-03',
    loja_id: 'loja-matriz-01',
    numero_os: 1040,
    cliente_id: 'cli-03',
    cliente_nome: 'Ana Clara Prado Ramos',
    cliente_telefone: '(11) 99444-1122',
    atendente_id: 'func-01',
    atendente_nome: 'Carlos Eduardo Mendes',
    montador_id: 'func-04',
    montador_nome: 'Roberto Silva (Montador)',
    status: 'PRONTO_RETIRADA',
    
    armacao_descricao: 'Armação Vogue Eyewear Feminina Tartaruga (VO5338)',
    armacao_referencia: 'VO5338-W44',
    armacao_propria: false,
    
    lente_descricao: 'Lente Monofocal CR-39 Antirreflexo Verde',
    lente_material: 'RESINA_1.56',
    lente_design: 'MONOFOCAL',
    tratamentos: ['Anti-Reflexo Standard', 'Anti-Risco'],
    
    dnp_od: 30.5,
    dnp_oe: 31.0,
    altura_od: 18.0,
    altura_oe: 18.0,
    
    valor_armacao: 540.00,
    valor_lentes: 390.00,
    valor_tratamentos: 90.00,
    valor_servicos_montagem: 30.00,
    custo_laboratorio_estimado: 110.00,
    valor_desconto: 50.00,
    valor_total: 1000.00,
    
    data_abertura: '2026-09-21T09:00:00Z',
    data_prometida: '2026-09-25T18:00:00Z',
    data_laboratorio_retorno: '2026-09-24T16:00:00Z',
    observacoes_internas: 'Montagem finalizada e testada no lensômetro. Perfeito!',
    created_at: '2026-09-21T09:00:00Z'
  }
];

export const INITIAL_VENDAS: VendaPDV[] = [
  {
    id: 'venda-01',
    loja_id: 'loja-matriz-01',
    numero_venda: 501,
    cliente_id: 'cli-03',
    cliente_nome: 'Ana Clara Prado Ramos',
    vendedor_id: 'func-03',
    vendedor_nome: 'Juliana Rocha (Consultora)',
    os_id: 'os-03',
    itens: [
      {
        produto_id: 'prod-03',
        nome: 'Armação Vogue Eyewear Feminina Tartaruga',
        quantidade: 1,
        preco_unitario: 540.00,
        desconto: 40.00,
        subtotal: 500.00
      },
      {
        produto_id: 'prod-07',
        nome: 'Spray Limpa Lentes Anti-Embaçante 60ml',
        quantidade: 2,
        preco_unitario: 25.00,
        desconto: 0.00,
        subtotal: 50.00
      }
    ],
    subtotal: 590.00,
    desconto_total: 40.00,
    valor_final: 550.00,
    forma_pagamento: 'PIX',
    status: 'CONCLUIDA',
    data_venda: '2026-09-26T11:20:00Z'
  },
  {
    id: 'venda-02',
    loja_id: 'loja-matriz-01',
    numero_venda: 502,
    cliente_nome: 'Cliente Avulso Balcão',
    vendedor_id: 'func-01',
    vendedor_nome: 'Carlos Eduardo Mendes',
    itens: [
      {
        produto_id: 'prod-06',
        nome: 'Óculos Solar Ray-Ban Wayfarer Classic G-15',
        quantidade: 1,
        preco_unitario: 920.00,
        desconto: 50.00,
        subtotal: 870.00
      }
    ],
    subtotal: 920.00,
    desconto_total: 50.00,
    valor_final: 870.00,
    forma_pagamento: 'CARTAO_CREDITO',
    parcelas: 6,
    status: 'CONCLUIDA',
    data_venda: '2026-09-26T15:45:00Z'
  }
];

export const INITIAL_TRANSACOES: TransacaoFinanceira[] = [
  {
    id: 'tra-01',
    loja_id: 'loja-matriz-01',
    tipo: 'RECEITA',
    categoria: 'Venda de Óculos Completo (O.S.)',
    descricao: 'Entrada O.S. #1042 - Mariana Silveira',
    valor: 1100.00,
    status: 'PAGO',
    data_vencimento: '2026-09-24',
    data_pagamento: '2026-09-24T10:35:00Z',
    cliente_ou_fornecedor: 'Mariana Silveira Albuquerque',
    forma_pagamento: 'PIX',
    os_id: 'os-01'
  },
  {
    id: 'tra-02',
    loja_id: 'loja-matriz-01',
    tipo: 'RECEITA',
    categoria: 'Venda Solar / Balcão',
    descricao: 'Venda PDV #502 - Ray-Ban Wayfarer',
    valor: 870.00,
    status: 'PAGO',
    data_vencimento: '2026-09-26',
    data_pagamento: '2026-09-26T15:45:00Z',
    cliente_ou_fornecedor: 'Cliente Balcão',
    forma_pagamento: 'Cartão Crédito 6x'
  },
  {
    id: 'tra-03',
    loja_id: 'loja-matriz-01',
    tipo: 'DESPESA',
    categoria: 'Laboratório Terceirizado',
    descricao: 'Fatura Mensal Surfaçagem - Essilor Lab',
    valor: 2840.00,
    status: 'PENDENTE',
    data_vencimento: '2026-10-05',
    cliente_ou_fornecedor: 'Essilor Digital Surfacing Lab'
  },
  {
    id: 'tra-04',
    loja_id: 'loja-matriz-01',
    tipo: 'DESPESA',
    categoria: 'Fornecedor de Armações',
    descricao: 'Reposição Coleção Luxottica (Ray-Ban / Oakley)',
    valor: 4350.00,
    status: 'PAGO',
    data_vencimento: '2026-09-20',
    data_pagamento: '2026-09-20T14:00:00Z',
    cliente_ou_fornecedor: 'Luxottica Brasil Distribuidora'
  }
];

export const INITIAL_LEADS_SAAS = [
  {
    id: 'lead-01',
    nome_responsavel: 'Antônio Rafael Nobre',
    nome_otica: 'Ótica Nova Visão',
    telefone: '(88) 99742-1823',
    email: 'rafael@oticanovavisao.com.br',
    cidade: 'Morada Nova',
    estado: 'CE',
    plano_interesse: 'PLANO_PRO_99',
    data_cadastro: '2026-09-25T14:30:00Z',
    trial_dias_restantes: 5,
    status: 'TRIAL_ATIVO',
    origem: 'WHATSAPP_DIRETO',
    observacoes: 'Testando o módulo de O.S. e receitas. Demonstrou bastante interesse no Kanban de laboratório.'
  },
  {
    id: 'lead-02',
    nome_responsavel: 'Mariana Duarte Costa',
    nome_otica: 'Ótica Clarividência',
    telefone: '(88) 98845-6677',
    email: 'contato@clarividenciaotica.com.br',
    cidade: 'Limoeiro do Norte',
    estado: 'CE',
    plano_interesse: 'PLANO_PRO_NF_149',
    data_cadastro: '2026-09-26T18:10:00Z',
    trial_dias_restantes: 6,
    status: 'TRIAL_ATIVO',
    origem: 'LANDING_PAGE',
    observacoes: 'Precisa emitir NFC-e no balcão e quer importar XML de lentes da Zeiss.'
  },
  {
    id: 'lead-03',
    nome_responsavel: 'Francisco Chagas Oliveira',
    nome_otica: 'Centro Óptico Jaguaribe',
    telefone: '(88) 99611-3322',
    email: 'chagas@centroopticojaguaribe.com.br',
    cidade: 'Russas',
    estado: 'CE',
    plano_interesse: 'PLANO_PRO_99',
    data_cadastro: '2026-09-21T09:15:00Z',
    trial_dias_restantes: 1,
    status: 'TRIAL_EXPIRANDO',
    origem: 'ANUNCIO_INSTAGRAM',
    observacoes: 'Teste encerra amanhã. Entrar em contato com desconto de primeira mensalidade!'
  },
  {
    id: 'lead-04',
    nome_responsavel: 'Fernanda Meireles Lima',
    nome_otica: 'Ótica Bella Vista',
    telefone: '(85) 99123-4567',
    email: 'fernanda@bellavistaotica.com.br',
    cidade: 'Fortaleza',
    estado: 'CE',
    plano_interesse: 'PLANO_PRO_NF_149',
    data_cadastro: '2026-09-18T11:00:00Z',
    trial_dias_restantes: 0,
    status: 'TRIAL_EXPIRADO',
    origem: 'INDICACAO',
    observacoes: 'Gostou do pupilômetro digital e da integração WhatsApp. Ofertar ativação com PIX.'
  },
  {
    id: 'lead-05',
    nome_responsavel: 'José Lucas Queiroz',
    nome_otica: 'Ótica São Francisco',
    telefone: '(88) 98112-9900',
    email: 'lucas@oticasaofrancisco.com.br',
    cidade: 'Quixadá',
    estado: 'CE',
    plano_interesse: 'PLANO_PRO_NF_149',
    data_cadastro: '2026-09-15T16:00:00Z',
    trial_dias_restantes: 0,
    status: 'CONVERTIDO_CLIENTE',
    origem: 'LANDING_PAGE',
    observacoes: 'Assinatura anual contratada e paga via PIX. Ativação concluída com sucesso.'
  }
];

export const INITIAL_TENANTS_SAAS: TenantSaaS[] = [
  {
    id: 'tenant-01',
    nome_fantasia: 'Ótica Visão Prime',
    razao_social: 'Visão Prime Comércio de Óptica Ltda',
    cnpj_cpf: '12.345.678/0001-90',
    responsavel_nome: 'Carlos Eduardo Mendes',
    responsavel_telefone: '(88) 99876-5432',
    responsavel_email: 'carlos@visaoprime.com.br',
    cidade: 'Morada Nova',
    estado: 'CE',
    plano: 'PLANO_PRO_NF_149',
    valor_mensalidade: 149.90,
    status: 'ATIVO',
    data_inicio: '2026-08-01',
    proximo_vencimento: '2026-10-01',
    total_filiais: 2,
    total_usuarios: 5,
    limite_notas_mes: 50,
    notas_emitidas_mes: 28,
    emissao_fiscal_ativa: true,
    certificado_a1_status: 'VALIDO',
    certificado_a1_validade: '15/10/2027',
    subconta_focus_id: 'sub_fc_visaoprime_01'
  },
  {
    id: 'tenant-02',
    nome_fantasia: 'Ótica São Francisco',
    razao_social: 'Queiroz & Filhos Óptica ME',
    cnpj_cpf: '24.987.123/0001-44',
    responsavel_nome: 'José Lucas Queiroz',
    responsavel_telefone: '(88) 98112-9900',
    responsavel_email: 'lucas@oticasaofrancisco.com.br',
    cidade: 'Quixadá',
    estado: 'CE',
    plano: 'PLANO_PRO_NF_149',
    valor_mensalidade: 149.90,
    status: 'ATIVO',
    data_inicio: '2026-09-15',
    proximo_vencimento: '2026-10-15',
    total_filiais: 1,
    total_usuarios: 3,
    limite_notas_mes: 50,
    notas_emitidas_mes: 12,
    emissao_fiscal_ativa: true,
    certificado_a1_status: 'VALIDO',
    certificado_a1_validade: '20/06/2027',
    subconta_focus_id: 'sub_fc_saofrancisco_02'
  },
  {
    id: 'tenant-03',
    nome_fantasia: 'Ótica Cristalina',
    razao_social: 'Cristalina Comércio de Óculos Ltda',
    cnpj_cpf: '33.112.554/0001-09',
    responsavel_nome: 'Patrícia Souza Gomes',
    responsavel_telefone: '(88) 99933-2211',
    responsavel_email: 'patricia@cristalinaotica.com.br',
    cidade: 'Iguatu',
    estado: 'CE',
    plano: 'PLANO_PRO_99',
    valor_mensalidade: 99.90,
    status: 'ATIVO',
    data_inicio: '2026-07-10',
    proximo_vencimento: '2026-10-10',
    total_filiais: 1,
    total_usuarios: 2,
    limite_notas_mes: 0,
    notas_emitidas_mes: 0,
    emissao_fiscal_ativa: false,
    certificado_a1_status: 'PENDENTE',
    subconta_focus_id: undefined
  },
  {
    id: 'tenant-04',
    nome_fantasia: 'Ótica Bella Vista',
    razao_social: 'Meireles & Lima Óptica Ltda',
    cnpj_cpf: '45.892.110/0001-72',
    responsavel_nome: 'Fernanda Meireles Lima',
    responsavel_telefone: '(85) 99123-4567',
    responsavel_email: 'fernanda@bellavistaotica.com.br',
    cidade: 'Fortaleza',
    estado: 'CE',
    plano: 'PLANO_PRO_NF_149',
    valor_mensalidade: 149.90,
    status: 'ATIVO',
    data_inicio: '2026-09-01',
    proximo_vencimento: '2026-10-01',
    total_filiais: 1,
    total_usuarios: 4,
    limite_notas_mes: 50,
    notas_emitidas_mes: 47,
    emissao_fiscal_ativa: true,
    certificado_a1_status: 'VALIDO',
    certificado_a1_validade: '12/11/2027',
    subconta_focus_id: 'sub_fc_bellavista_04'
  }
];

